sudo: required
dist: trusty
language: csharp
dotnet: 1.0.0-preview2-003121
mono: none

env:
- CONFIGURATION=Release NOTHREADS=10
- CONFIGURATION=Debug NOTHREADS=10
- CONFIGURATION=Release NOTHREADS=20
- CONFIGURATION=Debug NOTHREADS=20
- CONFIGURATION=Release NOTHREADS=50
- CONFIGURATION=Debug NOTHREADS=50

addons:
  apt:
    packages:
    - ldap-utils
    - gnutls-bin
    - ssl-cert
    - slapd

before_script:
  - whoami
  - mkdir /tmp/slapd
  # start setup ssl
  # prepare folders
  - mkdir -p /tmp/ssl/private
  - mkdir -p /tmp/ssl/certs
  # generate certs/keys
  - sudo certtool -p --outfile /tmp/ssl/private/ca_server.key
  - sudo certtool -s --load-privkey /tmp/ssl/private/ca_server.key --template test/conf/cert_template.conf --outfile /tmp/ssl/certs/ca_server.pem
  - sudo certtool -p --sec-param low --outfile /tmp/ssl/private/ldap_server.key
  - sudo certtool -c --load-privkey /tmp/ssl/private/ldap_server.key --load-ca-certificate /tmp/ssl/certs/ca_server.pem --load-ca-privkey /tmp/ssl/private/ca_server.key --template test/conf/cert_template.conf --outfile /tmp/ssl/certs/ldap_server.pem
  # permissions
  - sudo usermod -aG ssl-cert travis
  - sudo chown travis:ssl-cert /tmp/ssl/private/ldap_server.key /tmp/ssl/certs/ldap_server.pem /tmp/ssl/certs/ca_server.pem
  - sudo chmod 640 /tmp/ssl/private/ldap_server.key /tmp/ssl/certs/ldap_server.pem /tmp/ssl/certs/ca_server.pem
  # end setup ssl
  # start ssl
  - slapd -f test/conf/slapd.conf -h "ldap://localhost:4389 ldaps://localhost:4636" &
  # give openldap enough time to start
  - sleep 5
  # test to see that is running
  - ldapwhoami -H ldap://localhost:4389 -D "cn=root,dc=example,dc=com" -w password 
  - ldapadd -h localhost:4389 -D cn=root,dc=example,dc=com -w password -f test/conf/baseDn.ldif

script:
  - dotnet restore
  - dotnet build --configuration $CONFIGURATION **/project.json
  - dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/project.json
  - dotnet run --configuration $CONFIGURATION --project test/Novell.Directory.Ldap.NETStandard.StressTests/project.json $NOTHREADS 45
