sudo: required
dist: trusty
language: csharp
dotnet: 1.0.0-preview2-003121
mono: none

env:
- CONFIGURATION=Release NOTHREADS=10
- CONFIGURATION=Debug NOTHREADS=10
- CONFIGURATION=Release NOTHREADS=20
- CONFIGURATION=Debug NOTHREADS=20
- CONFIGURATION=Release NOTHREADS=50
- CONFIGURATION=Debug NOTHREADS=50

addons:
  apt:
    packages:
    - ldap-utils
    - slapd

before_script:
  - mkdir /tmp/slapd
  - slapd -f test/conf/slapd.conf -h ldap://localhost:4389 &
  # give openldap enough time to start
  - sleep 5
  # test to see that is running
  - ldapwhoami -H ldap://localhost:4389 -D "cn=root,dc=example,dc=com" -w password 
  - ldapadd -h localhost:4389 -D cn=root,dc=example,dc=com -w password -f test/conf/baseDn.ldif

script:
  - dotnet restore
  - dotnet build --configuration $CONFIGURATION **/project.json
  - dotnet test --configuration $CONFIGURATION test/Novell.Directory.Ldap.NETStandard.FunctionalTests/project.json
  - dotnet run --configuration $CONFIGURATION --project test/Novell.Directory.Ldap.NETStandard.StressTests/project.json $NOTHREADS 45
